'use client'

import { useState, useEffect } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { LOCAL_STORAGE_KEYS } from '@/lib/constants'
import type { AuditEvent } from '@/lib/types'
import { Download, Copy, CheckCheck, BarChart3, TrendingUp, Clock, Target } from 'lucide-react'

interface TicketData {
  id: string
  status: 'pending' | 'resolved' | 'contained'
  result?: {
    intent: { type: string }
  }
  createdAt: string
}

export default function AnalyticsPage() {
  const [tickets, setTickets] = useState<TicketData[]>([])
  const [auditLog, setAuditLog] = useState<AuditEvent[]>([])
  const [copied, setCopied] = useState(false)

  useEffect(() => {
    const storedTickets = localStorage.getItem(LOCAL_STORAGE_KEYS.TICKETS)
    const storedAudit = localStorage.getItem(LOCAL_STORAGE_KEYS.AUDIT_LOG)

    if (storedTickets) {
      setTickets(JSON.parse(storedTickets))
    }
    if (storedAudit) {
      setAuditLog(JSON.parse(storedAudit))
    }
  }, [])

  const stats = {
    totalTickets: tickets.length,
    containedTickets: tickets.filter(t => t.status === 'contained').length,
    wismoTickets: tickets.filter(t => t.result?.intent.type === 'WISMO').length,
    returnTickets: tickets.filter(t => t.result?.intent.type === 'RETURNS').length,
    containmentRate: tickets.length > 0
      ? Math.round((tickets.filter(t => t.status === 'contained').length / tickets.length) * 100)
      : 0,
  }

  const generateWeeklyReport = () => {
    const now = new Date()
    const weekAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000)

    const weekTickets = tickets.filter(t => new Date(t.createdAt) >= weekAgo)
    const weekContained = weekTickets.filter(t => t.status === 'contained').length

    return `
Weekly Resolution Report
========================
Period: ${weekAgo.toLocaleDateString()} - ${now.toLocaleDateString()}

Summary
-------
Total Tickets Processed: ${weekTickets.length}
Tickets Contained: ${weekContained}
Containment Rate: ${weekTickets.length > 0 ? Math.round((weekContained / weekTickets.length) * 100) : 0}%

Breakdown by Intent
-------------------
WISMO (Where Is My Order): ${weekTickets.filter(t => t.result?.intent.type === 'WISMO').length}
Returns/Refunds: ${weekTickets.filter(t => t.result?.intent.type === 'RETURNS').length}
Other: ${weekTickets.filter(t => t.result?.intent.type === 'OTHER').length}

Audit Events
------------
Total events logged: ${auditLog.filter(e => new Date(e.createdAt) >= weekAgo).length}

---
Generated by SiteGPT Verified Resolution Agent
${now.toISOString()}
`.trim()
  }

  const handleCopyReport = () => {
    navigator.clipboard.writeText(generateWeeklyReport())
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleDownloadReport = () => {
    const report = generateWeeklyReport()
    const blob = new Blob([report], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `sitegpt-report-${new Date().toISOString().split('T')[0]}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold">Analytics</h1>
        <p className="text-muted-foreground">Track your resolution performance</p>
      </div>

      {/* Stats Grid */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center gap-2">
              <BarChart3 className="h-4 w-4 text-muted-foreground" />
              <span className="text-sm text-muted-foreground">Total Tickets</span>
            </div>
            <div className="text-3xl font-bold mt-2">{stats.totalTickets}</div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center gap-2">
              <Target className="h-4 w-4 text-muted-foreground" />
              <span className="text-sm text-muted-foreground">Contained</span>
            </div>
            <div className="text-3xl font-bold mt-2">{stats.containedTickets}</div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center gap-2">
              <TrendingUp className="h-4 w-4 text-muted-foreground" />
              <span className="text-sm text-muted-foreground">Containment Rate</span>
            </div>
            <div className="text-3xl font-bold mt-2">{stats.containmentRate}%</div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center gap-2">
              <Clock className="h-4 w-4 text-muted-foreground" />
              <span className="text-sm text-muted-foreground">Audit Events</span>
            </div>
            <div className="text-3xl font-bold mt-2">{auditLog.length}</div>
          </CardContent>
        </Card>
      </div>

      {/* Intent Breakdown */}
      <Card>
        <CardHeader>
          <CardTitle>Tickets by Intent</CardTitle>
          <CardDescription>Distribution of ticket types</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex gap-4">
            <div className="flex-1 p-4 bg-blue-50 dark:bg-blue-950 rounded-lg">
              <Badge className="bg-blue-100 text-blue-800 mb-2">WISMO</Badge>
              <div className="text-2xl font-bold">{stats.wismoTickets}</div>
              <div className="text-sm text-muted-foreground">Where Is My Order</div>
            </div>
            <div className="flex-1 p-4 bg-purple-50 dark:bg-purple-950 rounded-lg">
              <Badge className="bg-purple-100 text-purple-800 mb-2">RETURNS</Badge>
              <div className="text-2xl font-bold">{stats.returnTickets}</div>
              <div className="text-sm text-muted-foreground">Return Requests</div>
            </div>
            <div className="flex-1 p-4 bg-gray-50 dark:bg-gray-900 rounded-lg">
              <Badge variant="outline" className="mb-2">OTHER</Badge>
              <div className="text-2xl font-bold">
                {stats.totalTickets - stats.wismoTickets - stats.returnTickets}
              </div>
              <div className="text-sm text-muted-foreground">Other Inquiries</div>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Weekly Report */}
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle>Weekly Report</CardTitle>
              <CardDescription>Generate and export your weekly performance report</CardDescription>
            </div>
            <div className="flex gap-2">
              <Button variant="outline" onClick={handleCopyReport}>
                {copied ? (
                  <>
                    <CheckCheck className="mr-2 h-4 w-4" />
                    Copied
                  </>
                ) : (
                  <>
                    <Copy className="mr-2 h-4 w-4" />
                    Copy
                  </>
                )}
              </Button>
              <Button onClick={handleDownloadReport}>
                <Download className="mr-2 h-4 w-4" />
                Download
              </Button>
            </div>
          </div>
        </CardHeader>
        <CardContent>
          <Tabs defaultValue="preview">
            <TabsList>
              <TabsTrigger value="preview">Preview</TabsTrigger>
              <TabsTrigger value="raw">Raw Text</TabsTrigger>
            </TabsList>
            <TabsContent value="preview" className="mt-4">
              <div className="bg-muted p-4 rounded-lg space-y-4">
                <div>
                  <h4 className="font-semibold">Summary</h4>
                  <ul className="text-sm text-muted-foreground mt-1">
                    <li>Total Tickets: {stats.totalTickets}</li>
                    <li>Contained: {stats.containedTickets}</li>
                    <li>Containment Rate: {stats.containmentRate}%</li>
                  </ul>
                </div>
                <div>
                  <h4 className="font-semibold">By Intent</h4>
                  <ul className="text-sm text-muted-foreground mt-1">
                    <li>WISMO: {stats.wismoTickets}</li>
                    <li>Returns: {stats.returnTickets}</li>
                  </ul>
                </div>
              </div>
            </TabsContent>
            <TabsContent value="raw" className="mt-4">
              <pre className="bg-muted p-4 rounded-lg text-sm whitespace-pre-wrap overflow-x-auto">
                {generateWeeklyReport()}
              </pre>
            </TabsContent>
          </Tabs>
        </CardContent>
      </Card>
    </div>
  )
}
